### ISSUE TITLE
Does `rake travis` send a webmention automatically?

### ISSUE THREAD

**Issue by chrisfinazzo** [maxandersen/xam.dk#121]
Hi Max,

I'm looking to set up sending webmentions on my own site - facilitated through [Bridgy](https://brid.gy). I noticed you have an integration with Travis CI in your `deploy` [action](https://github.com/maxandersen/xam.dk/blob/16a1b812e5657cd1abadded6e28c6dad231498b0/.github/workflows/deploy.yml#L43). In your experience, does building with Travis send a webmention from its source to the destination?

My host (Netlify) supports webmentions on its servers, but doesn't send them automatically when the site deploys - a key feature of Bridgy. Currently, I'm doing this work in a hand-edited shell script, which is rather unpleasant.

There is code in [this](https://herestomwiththeweather.com/2017/06/19/sending-webmentions-from-travis-ci-using-jekyll-indieweb-on-netlify/) post to do something similar, but your approach looks like it could be easier as I go about building out my own.

**Comment by maxandersen** [comment]
i've ditched travis and moved to github actions - i should probably remove that leftover code ;)

the thing that does webmentions for me is the jekyll webmentions plugin configured here: https://github.com/maxandersen/xam.dk/blob/master/_config.yml#L63
